### ISSUE TITLE
鏈接Dom的属性data-reload用法与文档描述不符

### ISSUE THREAD

**Issue by tunblr** [HenriettaSu/iframeTab#1]
[http://henrie.pursuitus.com/adminTemplate/](url)这个文档中说：

> 鏈接Dom
> `<a href="iframeTab-demo.html" data-num="0">主頁</a>`
> data-reload 為可選屬性，若存在，則再次點擊此鏈接時，iframe將被重新加載 

但是代码实现（/build/js/iframeTab.js第137行）为：
```
if (reload === 'ja'){
  $tabBody.find('iframe[data-iframe="' + link + '"]').attr('src', link);
}
```

所以应当是data-reload属性存在且等于"ja"时，再次点击链接，iframe将被重新加载
还请麻烦修改一下文档，感谢！

**Comment by HenriettaSu** [comment]
感謝報告錯誤，已修改完畢
已然是按文檔說的，只要data-reload屬性存在就可點擊重新加載，不再需要值為“ja”

**Comment by tunblr** [comment]
感谢！
