### ISSUE TITLE
太垃圾了

### ISSUE THREAD

**Issue by lanyur** [HenriettaSu/iframeTab#2]
跟Bootstrap绑定在一块，就没有一个完整独立的例子。浪费我一上午时间研究这个

**Comment by HenriettaSu** [comment]
@lanyur js屏蔽省jquery和iframetab也可以照常使用這個功能，也就屏蔽掉bootstrap.css會顯示不出而已（我已經標明了樣式需要自己配置，也標記了核心樣式）。你這一個上午可能需要先抽一兩個小時研究下css

**Comment by tunblr** [comment]
@lanyur 自己不会抽取Bootstrap的样式，还说别人垃圾，态度太恶劣了

**Comment by lanyur** [comment]
@Lihua93 哈哈，当时花了时间又没研究出来太愤怒了。
@HenriettaSu  sorry
